
import type { Listing, Review, Booking } from './types';
import { placeholderImages } from './placeholder-images';

export const listings: Listing[] = [
  {
    id: '9',
    title: 'Taj Mahal & Agra Fort Day Trip',
    type: 'tour',
    location: 'Agra, India',
    description: 'Witness the stunning beauty of the Taj Mahal at sunrise and explore the history of the magnificent Agra Fort on this full-day guided tour.',
    images: placeholderImages.filter(img => img.id.includes('tajmahal')),
    basePrice: 4500,
    capacity: 10,
    hostId: 'host8',
    amenities: ['Private Guide', 'AC Vehicle', 'Monument Tickets', 'Lunch Included'],
    rating: 4.9,
    reviewsCount: 2580,
    itinerary: [
        { day: 1, title: 'Sunrise at Taj Mahal', description: 'Experience the iconic monument in the beautiful morning light.' },
        { day: 1, title: 'Explore Agra Fort', description: 'Discover the history of the Mughal dynasty in this sprawling red sandstone fortress.' },
    ]
  },
  {
    id: '10',
    title: 'Jaipur: The Pink City Tour',
    type: 'tour',
    location: 'Jaipur, India',
    description: 'Discover the royal heritage of Jaipur with visits to Amber Fort, City Palace, Hawa Mahal, and the vibrant local markets.',
    images: placeholderImages.filter(img => img.id.includes('jaipur')),
    basePrice: 4000,
    capacity: 12,
    hostId: 'host8',
    amenities: ['Expert Guide', 'Elephant Ride at Amber Fort', 'All Entrance Fees'],
    rating: 4.8,
    reviewsCount: 1890,
  },
   {
    id: '11',
    title: 'Kerala Backwaters Houseboat Stay',
    type: 'package',
    location: 'Alleppey, India',
    description: 'Relax on a traditional houseboat as you cruise through the serene backwaters of Kerala. Enjoy authentic cuisine and picturesque landscapes.',
    images: placeholderImages.filter(img => img.id.includes('kerala')),
    basePrice: 12000,
    capacity: 4,
    hostId: 'host9',
    amenities: ['Private Houseboat', 'All Meals Included', 'Chef on Board', 'Overnight Stay'],
    rating: 4.9,
    reviewsCount: 950,
  },
  {
    id: '1',
    title: 'Eiffel Tower Summit & Seine River Cruise',
    type: 'tour',
    location: 'Paris, France',
    description: 'An unforgettable journey to the top of the Eiffel Tower, followed by a scenic cruise along the Seine River. See the heart of Paris from two unique perspectives.',
    images: placeholderImages.filter(img => img.id.includes('paris')),
    basePrice: 10000,
    capacity: 20,
    hostId: 'host1',
    amenities: ['Guided Tour', 'Skip-the-Line Access', 'Audio Guide'],
    rating: 4.9,
    reviewsCount: 1254,
    itinerary: [
        { day: 1, title: 'Eiffel Tower Ascent', description: 'Meet your guide and enjoy skip-the-line access to the Eiffel Tower summit for breathtaking views.' },
        { day: 1, title: 'Seine River Cruise', description: 'Embark on a one-hour cruise, admiring iconic landmarks like the Louvre and Notre Dame.' },
    ]
  },
  {
    id: '2',
    title: 'Mulia Resort & Villas Nusa Dua',
    type: 'hotel',
    location: 'Nusa Dua, Bali',
    description: 'A stunning beachfront resort offering luxurious rooms, a world-class spa, and multiple pools including the iconic Oasis Pool. Experience unparalleled luxury in Bali.',
    images: placeholderImages.filter(img => img.id.includes('mulia-bali')),
    basePrice: 28000,
    capacity: 2,
    hostId: 'host2',
    amenities: ['Beachfront', 'Oasis Pool', 'Spa & Wellness Center', '9 Restaurants & Bars', 'Kids Club'],
    rating: 4.9,
    reviewsCount: 3450,
  },
   {
    id: '15',
    title: 'The Oberoi Amarvilas',
    type: 'hotel',
    location: 'Agra, India',
    description: 'Just 600 metres from the Taj Mahal, this luxury hotel offers breathtaking views of the iconic monument from every room. Experience Mughal-inspired architecture and unparalleled hospitality.',
    images: placeholderImages.filter(img => img.id.includes('oberoi-agra')),
    basePrice: 45000,
    capacity: 2,
    hostId: 'host12',
    amenities: ['Taj Mahal View', 'Private Butler', 'Spa', 'Pool', 'Fine Dining'],
    rating: 5.0,
    reviewsCount: 1500,
  },
  {
    id: '3',
    title: 'Kyoto Cultural Immersion',
    type: 'tour',
    location: 'Kyoto, Japan',
    description: 'Explore the ancient temples, serene gardens, and traditional geisha districts of Kyoto. This tour offers a deep dive into Japanese culture and history.',
    images: placeholderImages.filter(img => img.id.includes('kyoto')),
    basePrice: 12500,
    capacity: 15,
    hostId: 'host3',
    amenities: ['Expert Guide', 'Tea Ceremony', 'Temple Entrance Fees'],
    rating: 4.9,
    reviewsCount: 982,
    itinerary: [
        { day: 1, title: 'Kinkaku-ji & Ryoan-ji', description: 'Visit the Golden Pavilion and the famous rock garden.' },
        { day: 1, title: 'Gion District Walk', description: 'Explore the historic geisha district and enjoy a traditional tea ceremony.' },
    ]
  },
  {
    id: '4',
    title: 'Alpine Ski Adventure Package',
    type: 'package',
    location: 'Zermatt, Switzerland',
    description: 'A 7-day all-inclusive ski package in the Swiss Alps. Includes lift passes, luxury chalet accommodation, and gourmet meals with views of the Matterhorn.',
    images: placeholderImages.filter(img => img.id.includes('alps')),
    basePrice: 224000,
    capacity: 4,
    hostId: 'host4',
    amenities: ['Ski-in/Ski-out', 'All-Inclusive', 'Sauna', 'Fireplace'],
    rating: 5.0,
    reviewsCount: 340,
  },
   {
    id: '16',
    title: 'The Ritz-Carlton, Kyoto',
    type: 'hotel',
    location: 'Kyoto, Japan',
    description: 'Located on the banks of the Kamogawa river, this hotel offers a serene luxury experience with traditional Japanese design elements and five-star amenities.',
    images: placeholderImages.filter(img => img.id.includes('ritz-kyoto')),
    basePrice: 75000,
    capacity: 3,
    hostId: 'host13',
    amenities: ['River View', 'Indoor Pool', 'Michelin-Star Restaurant', 'Spa', 'Concierge'],
    rating: 4.9,
    reviewsCount: 650,
  },
  {
    id: '5',
    title: 'Ancient Rome & Colosseum Tour',
    type: 'tour',
    location: 'Rome, Italy',
    description: 'Step back in time with a guided tour of the Colosseum, Roman Forum, and Palatine Hill. Discover the stories of gladiators, emperors, and ancient Roman life.',
    images: placeholderImages.filter(img => img.id.includes('rome')),
    basePrice: 8000,
    capacity: 25,
    hostId: 'host1',
    amenities: ['Archaeologist Guide', 'Skip-the-Line Access', 'Headsets'],
    rating: 4.7,
    reviewsCount: 2109,
  },
  {
    id: '12',
    title: 'Spiritual Tour of the Golden Temple',
    type: 'tour',
    location: 'Amritsar, India',
    description: 'Experience the divine atmosphere of the Golden Temple, the holiest shrine in Sikhism. Participate in the langar (community kitchen) and witness the Palki Sahib ceremony.',
    images: placeholderImages.filter(img => img.id.includes('goldentemple')),
    basePrice: 3000,
    capacity: 15,
    hostId: 'host10',
    amenities: ['Local Guide', 'Head Covering Provided', 'Langar Experience'],
    rating: 5.0,
    reviewsCount: 3500,
  },
  {
    id: '7',
    title: 'Grand Canyon Helicopter Tour',
    type: 'tour',
    location: 'Arizona, USA',
    description: 'Experience the Grand Canyon from a breathtaking aerial perspective. This helicopter tour flies over the most scenic parts of this natural wonder.',
    images: placeholderImages.filter(img => img.id.includes('canyon')),
    basePrice: 24000,
    capacity: 6,
    hostId: 'host6',
    amenities: ['Helicopter Flight', 'Hotel Pickup/Drop-off', 'Live Commentary'],
    rating: 4.9,
    reviewsCount: 789,
  },
  {
    id: '8',
    title: 'Serengeti Safari Package',
    type: 'package',
    location: 'Tanzania, Africa',
    description: 'A 5-day safari through the Serengeti National Park. Witness the Great Migration, spot the "Big Five," and stay in luxury safari lodges.',
    images: placeholderImages.filter(img => img.id.includes('safari')),
    basePrice: 280000,
    capacity: 6,
    hostId: 'host7',
    amenities: ['4x4 Vehicle', 'Expert Guide', 'Lodge Accommodation', 'All Meals Included'],
    rating: 5.0,
    reviewsCount: 451,
  },
  {
    id: '13',
    title: 'Varanasi Ghats & Ganga Aarti',
    type: 'tour',
    location: 'Varanasi, India',
    description: 'Witness the mesmerizing evening Ganga Aarti ceremony from a boat on the sacred river. Explore the ancient ghats and learn about the spiritual heart of India.',
    images: placeholderImages.filter(img => img.id.includes('varanasi')),
    basePrice: 3500,
    capacity: 20,
    hostId: 'host10',
    amenities: ['Boat Ride', 'Local Guide', 'Spiritual Narration'],
    rating: 4.9,
    reviewsCount: 2200,
  },
  {
    id: '14',
    title: 'Sun & Sand: Goa Beach Paradise',
    type: 'package',
    location: 'Goa, India',
    description: 'A relaxing 4-day beach holiday in Goa. Enjoy the sun-kissed beaches, vibrant nightlife, and delicious seafood at a charming beachside resort.',
    images: placeholderImages.filter(img => img.id.includes('goa')),
    basePrice: 15000,
    capacity: 2,
    hostId: 'host11',
    amenities: ['Beachfront Resort', 'Daily Breakfast', 'Water Sports Coupon', 'Airport Transfer'],
    rating: 4.7,
    reviewsCount: 1750,
  },
  {
    id: '17',
    title: 'Four Seasons Hotel George V',
    type: 'hotel',
    location: 'Paris, France',
    description: 'An art-deco landmark built in 1928, the Four Seasons George V is nestled in the Golden Triangle of Paris, just off the historic Champs-Élysées.',
    images: placeholderImages.filter(img => img.id.includes('four-seasons-paris')),
    basePrice: 120000,
    capacity: 2,
    hostId: 'host1',
    amenities: ['Michelin-starred dining', 'Luxury Spa', 'Indoor Pool', 'Eiffel Tower Views'],
    rating: 4.9,
    reviewsCount: 800,
  },
  {
    id: '18',
    title: 'Hotel de Russie, a Rocco Forte Hotel',
    type: 'hotel',
    location: 'Rome, Italy',
    description: 'A true Roman icon, Hotel de Russie is a tranquil oasis in the heart of the city between the Spanish Steps and Piazza del Popolo. It features a stunning terraced garden.',
    images: placeholderImages.filter(img => img.id.includes('russie-rome')),
    basePrice: 95000,
    capacity: 3,
    hostId: 'host1',
    amenities: ['Secret Garden', 'De La Ville Spa', 'Le Jardin de Russie Restaurant', 'Central Location'],
    rating: 4.9,
    reviewsCount: 750,
  },
  {
    id: '19',
    title: 'Bellagio Hotel & Casino',
    type: 'hotel',
    location: 'Las Vegas, USA',
    description: 'An iconic Las Vegas resort famous for its grand scale, elegance, and the spectacular Fountains of Bellagio. Offers a premier casino, fine dining, and world-class entertainment.',
    images: placeholderImages.filter(img => img.id.includes('bellagio-vegas')),
    basePrice: 40000,
    capacity: 4,
    hostId: 'host6',
    amenities: ['Fountain Views', 'Casino', 'Multiple Pools', 'Fine Dining', 'Conservatory & Botanical Gardens'],
    rating: 4.7,
    reviewsCount: 25000,
  },
  {
    id: '20',
    title: 'Four Seasons Safari Lodge Serengeti',
    type: 'hotel',
    location: 'Tanzania, Africa',
    description: 'Deep in the heart of the Serengeti, feel at one with the wildlife at our Lodge. Watch elephants and more at our watering hole, all from the comfort of your room or our infinity pool.',
    images: placeholderImages.filter(img => img.id.includes('four-seasons-serengeti')),
    basePrice: 150000,
    capacity: 2,
    hostId: 'host7',
    amenities: ['Watering Hole Views', 'Infinity Pool', 'Guided Safaris', 'Spa'],
    rating: 5.0,
    reviewsCount: 600,
  },
  {
    id: '21',
    title: 'The Plaza, A Fairmont Managed Hotel',
    type: 'hotel',
    location: 'New York, USA',
    description: 'A timeless landmark at the corner of Central Park, The Plaza offers a blend of historic elegance and modern luxury. Experience the iconic Palm Court and Guerlain Spa.',
    images: placeholderImages.filter(img => img.id.includes('plaza-nyc')),
    basePrice: 85000,
    capacity: 2,
    hostId: 'host14',
    amenities: ['Central Park Location', 'Fine Dining', 'Luxury Spa', 'Butler Service'],
    rating: 4.8,
    reviewsCount: 2200,
  },
  {
    id: '22',
    title: 'The Savoy',
    type: 'hotel',
    location: 'London, UK',
    description: 'Set on the River Thames, this iconic hotel has hosted royalty, world leaders and rock stars. Enjoy elegant rooms, Gordon Ramsay\'s Savoy Grill and the legendary American Bar.',
    images: placeholderImages.filter(img => img.id.includes('savoy-london')),
    basePrice: 78000,
    capacity: 2,
    hostId: 'host15',
    amenities: ['River Thames Views', 'Michelin-starred Dining', 'Indoor Pool', '24-hour Butler Service'],
    rating: 4.9,
    reviewsCount: 1900,
  },
  {
    id: '23',
    title: 'Park Hyatt Sydney',
    type: 'hotel',
    location: 'Sydney, Australia',
    description: 'With a coveted location between the Sydney Opera House and Harbour Bridge, Park Hyatt Sydney offers an intimate, residential-style hotel with architecture, art and design that reflects the Australian landscape.',
    images: placeholderImages.filter(img => img.id.includes('park-hyatt-sydney')),
    basePrice: 65000,
    capacity: 3,
    hostId: 'host16',
    amenities: ['Opera House Views', 'Rooftop Pool', 'Private Balconies', 'Waterfront Dining'],
    rating: 4.9,
    reviewsCount: 1300,
  },
  {
    id: '24',
    title: 'Burj Al Arab Jumeirah',
    type: 'hotel',
    location: 'Dubai, UAE',
    description: 'The distinctive sail-shaped silhouette of Burj Al Arab is more than just a stunning hotel, it is a symbol of modern Dubai. A hotel of unparalleled luxury with duplex suites and private butlers.',
    images: placeholderImages.filter(img => img.id.includes('burj-al-arab-dubai')),
    basePrice: 180000,
    capacity: 4,
    hostId: 'host17',
    amenities: ['Private Beach', 'Underwater Restaurant', 'Rolls-Royce Fleet', 'Helipad', 'Personal Butler'],
    rating: 5.0,
    reviewsCount: 3000,
  },
  {
    id: '25',
    title: 'The Gritti Palace, a Luxury Collection Hotel',
    type: 'hotel',
    location: 'Venice, Italy',
    description: 'With a history dating to 1475, The Gritti Palace is a Venetian legend. Overlooking the Grand Canal, the hotel boasts some of the most enchanting views of the city.',
    images: placeholderImages.filter(img => img.id.includes('gritti-venice')),
    basePrice: 110000,
    capacity: 2,
    hostId: 'host18',
    amenities: ['Grand Canal Views', 'Riva Yacht Experience', 'Cooking School', 'Historic Decor'],
    rating: 4.9,
    reviewsCount: 900,
  },
  {
    id: '26',
    title: 'Katikies Hotel',
    type: 'hotel',
    location: 'Santorini, Greece',
    description: 'Perched on the cliffs of Oia, Katikies offers breathtaking views of the Caldera, infinity pools and luxurious, minimalist suites. A quintessential Santorini experience.',
    images: placeholderImages.filter(img => img.id.includes('katikies-santorini')),
    basePrice: 70000,
    capacity: 2,
    hostId: 'host19',
    amenities: ['Caldera Views', 'Infinity Pools', 'Fine Dining', 'Champagne Bar'],
    rating: 4.9,
    reviewsCount: 1200,
  },
  {
    id: '27',
    title: 'Copacabana Palace, A Belmond Hotel',
    type: 'hotel',
    location: 'Rio de Janeiro, Brazil',
    description: 'An Art Deco icon overlooking Copacabana Beach. Since 1923, this glamorous landmark has been welcoming the rich and famous. Enjoy the semi-Olympic pool and elegant restaurants.',
    images: placeholderImages.filter(img => img.id.includes('copacabana-rio')),
    basePrice: 45000,
    capacity: 3,
    hostId: 'host20',
    amenities: ['Beachfront Location', 'Large Swimming Pool', 'Top-tier Restaurants', 'Tennis Court'],
    rating: 4.8,
    reviewsCount: 1500,
  },
  {
    id: '28',
    title: 'Marriott Mena House, Cairo',
    type: 'hotel',
    location: 'Cairo, Egypt',
    description: 'A historic palace hotel with its own private gardens, offering unmatched views of the Great Pyramids. Walk through lush gardens and enjoy a blend of history and modern luxury.',
    images: placeholderImages.filter(img => img.id.includes('marriott-mena-cairo')),
    basePrice: 35000,
    capacity: 2,
    hostId: 'host21',
    amenities: ['Pyramid Views', '40 Acres of Gardens', 'Swimming Pool', 'Spa', 'Multiple Restaurants'],
    rating: 4.7,
    reviewsCount: 1800,
  },
  {
    id: '29',
    title: 'Marina Bay Sands',
    type: 'hotel',
    location: 'Singapore',
    description: 'An architectural marvel defining the Singapore skyline. Famous for its incredible rooftop infinity pool, SkyPark, and world-class shopping, dining, and entertainment.',
    images: placeholderImages.filter(img => img.id.includes('marina-bay-sands-sg')),
    basePrice: 55000,
    capacity: 3,
    hostId: 'host22',
    amenities: ['Rooftop Infinity Pool', 'SkyPark Observation Deck', 'Casino', 'Direct Mall Access'],
    rating: 4.7,
    reviewsCount: 15000,
  },
  {
    id: '30',
    title: 'The Upper House',
    type: 'hotel',
    location: 'Hong Kong',
    description: 'An intimate and serene hotel high above the bustling city. The Upper House is designed to provide a sense of calm, with spacious rooms and stunning views of Victoria Harbour.',
    images: placeholderImages.filter(img => img.id.includes('upper-house-hk')),
    basePrice: 68000,
    capacity: 2,
    hostId: 'host23',
    amenities: ['Panoramic Harbour Views', 'Paperless Check-in', 'Complimentary Maxi-Bar', 'Luxury Wellness'],
    rating: 4.9,
    reviewsCount: 950,
  },
  {
    id: '31',
    title: 'The Taj Mahal Palace, Mumbai',
    type: 'hotel',
    location: 'Mumbai, India',
    description: 'An iconic, sea-facing landmark in the heart of Mumbai, standing in stately grandeur since 1903. This flagship hotel of the Taj Group offers panoramic views of the Arabian Sea and the Gateway of India.',
    images: placeholderImages.filter(img => img.id.includes('taj-mumbai')),
    basePrice: 25000,
    capacity: 2,
    hostId: 'host24',
    amenities: ['Sea View', 'Jiva Spa', '9 Iconic Restaurants', 'Palace Butler Service', 'Pool'],
    rating: 4.9,
    reviewsCount: 12000
  },
  {
    id: '32',
    title: 'Taj Lake Palace, Udaipur',
    type: 'hotel',
    location: 'Udaipur, India',
    description: 'A spectacular floating vision in white marble on Lake Pichola, the Taj Lake Palace is a former royal summer palace. Arrive by boat and enter a world of fairytale romance.',
    images: placeholderImages.filter(img => img.id.includes('taj-udaipur')),
    basePrice: 55000,
    capacity: 2,
    hostId: 'host25',
    amenities: ['Lake Views', 'Royal Butlers', 'Jiva Spa Boat', 'Heritage Walks', 'Astrologer'],
    rating: 5,
    reviewsCount: 3500
  },
  {
    id: '33',
    title: 'Rambagh Palace, Jaipur',
    type: 'hotel',
    location: 'Jaipur, India',
    description: 'Once the residence of the Maharaja of Jaipur, Rambagh Palace is a living legend. Stroll through the elaborate Mughal gardens and experience royal hospitality.',
    images: placeholderImages.filter(img => img.id.includes('taj-jaipur')),
    basePrice: 48000,
    capacity: 2,
    hostId: 'host26',
    amenities: ['Mughal Gardens', 'Indoor & Outdoor Pools', 'Jiva Spa', 'Polo Bar', 'Vintage Car City Tours'],
    rating: 4.9,
    reviewsCount: 2800
  },
  {
    id: '34',
    title: 'Lalitha Mahal Palace Hotel',
    type: 'hotel',
    location: 'Mysore, India',
    description: 'The second largest palace in Mysore, Lalitha Mahal offers an opulent stay with architecture inspired by St. Paul\'s Cathedral in London. Experience the grandeur of a bygone royal era.',
    images: placeholderImages.filter(img => img.id.includes('lalitha-mahal')),
    basePrice: 18000,
    capacity: 2,
    hostId: 'host27',
    amenities: ['Heritage Property', 'Royal Ballroom', 'Swimming Pool', 'Billiards Room', 'Panoramic Views'],
    rating: 4.6,
    reviewsCount: 1200
  },
  {
    id: '35',
    title: 'ITC Grand Chola, a Luxury Collection Hotel',
    type: 'hotel',
    location: 'Chennai, India',
    description: 'Inspired by the imperial Chola Dynasty, this majestic hotel is a modern palace in the heart of Chennai. It boasts grand architecture, luxurious interiors, and a host of world-class amenities.',
    images: placeholderImages.filter(img => img.id.includes('itc-chola')),
    basePrice: 15000,
    capacity: 2,
    hostId: 'host28',
    amenities: ['10 F&B Outlets', 'Three Swimming Pools', 'Kaya Kalp Spa', 'LEED Platinum Certified', 'Butler Service'],
    rating: 4.8,
    reviewsCount: 4500
  },
  {
    id: '36',
    title: 'Novotel Goa Candolim',
    type: 'hotel',
    location: 'Goa, India',
    description: 'Located in the vibrant heart of North Goa, close to Candolim Beach, this resort offers a perfect blend of relaxation and fun with family-friendly amenities and stylish modern rooms.',
    images: placeholderImages.filter(img => img.id.includes('novotel-goa')),
    basePrice: 9000,
    capacity: 3,
    hostId: 'host29',
    amenities: ['Outdoor Pools', 'Kids Play Area', 'Fitness Center', 'Walking distance to beach', 'Sports Zone'],
    rating: 4.5,
    reviewsCount: 3200
  },
  {
    id: '37',
    title: 'The Ultimate World Wanderer',
    type: 'package',
    location: 'Global',
    description: 'A once-in-a-lifetime 30-day journey across the globe, visiting iconic landmarks and hidden gems. From the romance of Paris to the wonders of Machu Picchu, this is the ultimate adventure.',
    images: placeholderImages.filter(img => img.id.includes('world-tour')),
    basePrice: 1500000,
    capacity: 12,
    hostId: 'host30',
    amenities: ['Business Class Flights', '5-Star Hotels', 'Private Tours', 'All-Inclusive'],
    rating: 5.0,
    reviewsCount: 75,
    itinerary: [
      { day: 1, title: 'Paris: The City of Light', description: 'Arrival in Paris, check into your luxury hotel. Evening Eiffel Tower tour and welcome dinner.' },
      { day: 5, title: 'Rome: The Eternal City', description: 'Fly to Rome. Private tour of the Colosseum and Roman Forum.' },
      { day: 10, title: 'Giza: Ancient Wonders', description: 'Fly to Cairo. Visit the Great Pyramids of Giza and the Sphinx.' },
      { day: 15, title: 'Agra: The Symbol of Love', description: 'Travel to Agra for a sunrise visit to the magnificent Taj Mahal.' },
      { day: 20, title: 'Kyoto: Imperial Japan', description: 'Fly to Kyoto. Explore ancient temples, serene gardens, and the Gion district.' },
      { day: 25, title: 'Cusco: Gateway to Machu Picchu', description: 'Fly to Peru and take a scenic train journey to the lost city of Machu Picchu.' },
    ]
  },
  {
    id: '38',
    title: 'Essence of France',
    type: 'package',
    location: 'France',
    description: 'A 10-day tour exploring the best of France. From the romantic streets of Paris to the sunny vineyards of Bordeaux and the glamorous French Riviera.',
    images: placeholderImages.filter(img => img.id.includes('france-tour')),
    basePrice: 350000,
    capacity: 16,
    hostId: 'host1',
    amenities: ['High-Speed Train Travel', 'Boutique Hotels', 'Wine Tasting', 'Cooking Class'],
    rating: 4.8,
    reviewsCount: 150,
    itinerary: [
      { day: 1, title: 'Arrival in Paris', description: 'Explore Montmartre and enjoy a welcome dinner.' },
      { day: 4, title: 'Bordeaux Vineyards', description: 'Travel to Bordeaux for wine tasting and a chateau stay.' },
      { day: 7, title: 'French Riviera', description: 'Journey to Nice and explore the stunning coastline, including Monaco.' },
    ]
  },
  {
    id: '39',
    title: 'Incredible India: A Golden Triangle Journey',
    type: 'package',
    location: 'India',
    description: 'A classic 7-day tour of India\'s Golden Triangle. Discover the history and culture of Delhi, the iconic Taj Mahal in Agra, and the royal splendor of Jaipur.',
    images: placeholderImages.filter(img => img.id.includes('india-tour')),
    basePrice: 95000,
    capacity: 20,
    hostId: 'host8',
    amenities: ['Private AC Vehicle', '5-Star Accommodation', 'Expert Local Guides', 'Rickshaw Ride in Delhi'],
    rating: 4.8,
    reviewsCount: 550,
    itinerary: [
      { day: 1, title: 'Arrival in Delhi', description: 'Explore Old and New Delhi, including Humayun\'s Tomb and Qutub Minar.' },
      { day: 3, title: 'The Taj Mahal, Agra', description: 'Drive to Agra and witness the beauty of the Taj Mahal and Agra Fort.' },
      { day: 5, title: 'The Pink City, Jaipur', description: 'Travel to Jaipur and visit Amber Fort, City Palace, and Hawa Mahal.' },
    ]
  },
  {
    id: '40',
    title: 'New Zealand Adventure: Fjords & Mountains',
    type: 'package',
    location: 'New Zealand',
    description: 'An epic 12-day adventure across New Zealand\'s South Island. From the adventure capital of Queenstown to the majestic Milford Sound and stunning glaciers.',
    images: placeholderImages.filter(img => img.id.includes('nz-tour')),
    basePrice: 450000,
    capacity: 14,
    hostId: 'host31',
    amenities: ['Scenic Flights', 'Cruise on Milford Sound', 'Heli-Hike on a Glacier', 'Luxury Lodges'],
    rating: 4.9,
    reviewsCount: 220,
    itinerary: [
      { day: 1, title: 'Queenstown: Adventure Capital', description: 'Arrival in Queenstown. Explore the city and enjoy lake views.' },
      { day: 4, title: 'Milford Sound Cruise', description: 'Journey to the stunning Milford Sound for an overnight cruise through the fjord.' },
      { day: 8, title: 'Franz Josef Glacier', description: 'Travel up the West Coast to experience a guided heli-hike on the Franz Josef Glacier.' },
    ]
  }
];

export const reviews: Review[] = [
    { id: 'r1', listingId: '1', userId: 'u1', userName: 'Alice', userAvatar: 'https://picsum.photos/seed/avatar1/40/40', rating: 5, comment: 'Absolutely breathtaking! The skip-the-line access was a lifesaver.', createdAt: '2023-10-15' },
    { id: 'r2', listingId: '1', userId: 'u2', userName: 'Bob', userAvatar: 'https://picsum.photos/seed/avatar2/40/40', rating: 5, comment: 'The river cruise was so romantic. Seeing Paris sparkle at night was magical.', createdAt: '2023-10-12' },
    { id: 'r3', listingId: '2', userId: 'u3', userName: 'Charlie', userAvatar: 'https://picsum.photos/seed/avatar3/40/40', rating: 5, comment: 'This was the most incredible resort I have ever stayed at. Pure luxury!', createdAt: '2023-09-20' },
    { id: 'r4', listingId: '9', userId: 'u4', userName: 'Rohan', userAvatar: 'https://picsum.photos/seed/avatar4/40/40', rating: 5, comment: 'Seeing the Taj Mahal at sunrise was a dream come true. Our guide was fantastic!', createdAt: '2024-02-20' },
    { id: 'r5', listingId: '11', userId: 'u5', userName: 'Priya', userAvatar: 'https://picsum.photos/seed/avatar5/40/40', rating: 5, comment: 'The houseboat experience was so peaceful and unique. The food was delicious!', createdAt: '2024-01-10' },
];

export const bookings: Booking[] = [
    { id: 'b1', listingId: '3', userId: 'user123', startDate: '2024-08-10', endDate: '2024-08-11', guests: 2, priceTotal: 25000, status: 'confirmed', paymentIntentId: 'pi_1', createdAt: '2024-06-01' },
    { id: 'b2', listingId: '2', userId: 'user123', startDate: '2024-07-05', endDate: '2024-07-10', guests: 2, priceTotal: 140000, status: 'confirmed', paymentIntentId: 'pi_2', createdAt: '2024-05-15' },
    { id: 'b3', listingId: '4', userId: 'user123', startDate: '2023-12-20', endDate: '2023-12-27', guests: 4, priceTotal: 224000, status: 'confirmed', paymentIntentId: 'pi_3', createdAt: '2023-10-01' },
];

    

    

